### PR TITLE
Pull request for Docker compatibility

### PR DESCRIPTION
**Pull request by walter-bd**
Docker compatibility for Kitty with requested changes.

### CODE REVIEW

**Comment by a-lexer** [comment]
Perhaps take the chance to upgrade to python 3.10?

**Comment by walter-bd** [comment]
Yes, we can upgrade the python version if there's no problem with it; I just put the version that was used in the DO environment.

**Comment by a-lexer** [comment]
I had to upgrade the 'attrs' dependency (https://github.com/olliequ/KittyBot/pull/34/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) for it to work for me, but that may have been a local issue. Doesn't seem to have caused any problems upgrading it anyway.

**Comment by walter-bd** [comment]
I can update the requirements.txt as well. Let me do that and push the changes

**Pull request merged**
